### ISSUE TITLE
Basic backend functionality using database

### ISSUE THREAD

**Issue by alexeast99** [xlab-classes/cse442-spring2022-team-init-d#37]
- [x] Functionality to create a user
- [x] Functionality to login a user, if they exist and their password is correct
- [x] Functionality to change a user's password
- [x] Write tests in PHP to test that the functionality was implemented correctly

**Task Tests**
*Test 1 -- Creating a user*
1. Add a user to the database with the following credentials:
Name ----- Jon Doe [string]
Email ------ jon.doe@gmail.com [string]
Password - password [string]
Address -- 123 Apple Orchard Rd [string]
Zipcode -- 14541 [int]
Birthday -- 12/01/1980 [string]
Using the `create_user()` function, and store the result in a variable called `$create_result`.

<br>

2. Ensure that `$create_result` is equal to 0. If it's not, the test should fail.

<br>

3. Query the database using the `exec_query` function, with the following arguments:
`$query = "SELECT * FROM Users WHERE email=?"`
`$data = ["jon.doe@gmail.com"]`
and store the result in a variable called `$result`

<br>

4. Ensure that `$result`:
* Is not `NULL`
* Is not `False`
* Contains more 1 row
If `$result` is `NULL`, `False`, or contains anything but 1 row, the test should fail

<br>

5. Call `$result->fetch_assoc()` and store the result in a variable called `$arr`

<br>

6. Ensure that `$arr`
* Is not `NULL`
* Is not `False`
If `$arr` is any of these, the test should fail

<br>

7. Access the data inside `$arr`, and ensure that
* `$arr["name"]` is "Jon Doe"
* `$arr["email"]` is "jon.doe@gmail.com"
* `$arr["password"]` is "password"
* `$arr["street_address"]` is "123 Apple Orchard Rd"
* `$arr["zipcode"]` is "14541"
* `$arr["birthday"]` is "12/01/1980"
If any of these values are incorrect, the test should fail

<br>

8. If all of the previous conditions were met successfully, the test should pass

*Test 2*
*Test 2 -- Testing Login*
1. Create a user with the following credentials:
Name ----- Test [string]
Email ------ test[string]
Password - a [string]
Address -- b [string]
Zipcode -- 14541 [int]
Birthday -- d [string]
Using the `create_user()` function, and store the result in a variable called `$test_user`.

<br>

2. Ensure that `$test_user` is equal to 1. If it's not, the test should fail.

<br>

3. Check that the user isn't already signed in and if they are the tests should fail.

<br>

4. Sign in the test user actually this time and save the result of that function call into a variable named '$test'

<br>

5. Assert that the value of '$test' is equal to 1 and if not the tests will fail
<br>

6. If all of the previous conditions were met successfully, the test should pass

**Comment by alexeast99** [comment]
Use the API from the [hackmd.io](https://hackmd.io/@SIu9VvbVTAiMpbt0IPxIfg/BJXC4cTx5) document specifying the DB API.
